---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
- namespace.yaml
- zalando-secret.yaml
- secret.yaml
- keydb
- postgres.yaml
- helmrelease.yaml
- volsync-pvc
