---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ytars
resources:
- secret.yaml
- ../../base/ytars
patches:
- target:
    kind: HelmRelease
    name: ytars-app-template
  path: patch.yaml
